services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.example
    ports:
      - "8188:8188"
    volumes:
      - comfyui-workspace:/workspace
    stdin_open: true
    tty: true

volumes:
  comfyui-workspace:
